### ISSUE TITLE
Improvement of the program

### ISSUE THREAD

**Issue by justkey007** [joonhocho/tscpaths#10]
Hello! I cloned your job and I arranged it. You can visit it at https://github.com/justkey007/tsc-alias.
Currently, just take the typed configuration and without the other options. Excuse me I speak French which I used the machine translation but my message was poorly translated and I noticed too late.

**Comment by jplew** [comment]
@justkey007 I tried your version and there were some issues auto-inferring the source and output directories, a difficulty @joonhocho alludes to in his README.

Specifically, your `normalizePath` call was failing with an `TypeError: expected path to be a string` error. I investigated a bit and learned that it was because it was trying to normalize three paths:

```
{ path: '/Users/jplew/platform/cli/src', type: 'string' }
{ path: '/Users/jplew/platform/cli/lib', type: 'string' }
{ path: undefined, type: 'undefined' }
```
The third, undefined, path was causing the error. I can provide more details if you're interested.

If you can get it to auto-detect directories reliably that would be cool. But for now I'm sticking with this lib because it just works; having to manually specify the source and output directories is a trade-off I can live with.

nice work @joonhocho!

**Comment by justkey007** [comment]
Hello @jplew ,
Thank you very much for testing my version,
If I changed @joonhocho's work it's because it did not work for me because of my configuration. Now the problem is solved and it works in the general case. In my project I was trying to reference paths outside my project because I was doing code sharing between different projects.

You can add aliases that reference other projects outside your tsconfig.json project by providing a relative path to the baseUrl.

**Comment by justkey007** [comment]
Hello @jplew ,
Thank you very much for testing my version,
If I changed @joonhocho  's work it's because it did not work for me because of my configuration. Now the problem is solved and it works in the general case. In my project I was trying to reference paths outside my project because I was doing code sharing between different projects.

You can add aliases that reference other projects outside your tsconfig.json project by providing a relative path to the baseUrl.

**Comment by justkey007** [comment]
Hello @jplew,
A friend who has also tested my version has just told me about an error and I just corrected it. I do not know if you have noticed the error too. For that I inform you in case you use also the program and do not hesitate to inform me of other errors noticed. I am native French so I often use the translation and sometimes the tool changes the meaning of my sentences (I apologize for that).
======= What has been corrected and added =======
Fixed to properly support aliases in the form 'path/*' and optional specification of tsconfig.json and added numbers of replaced files.
